timeout: 30m
steps:
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME/.m2
      - .
  - name: gcr.io/$PROJECT_ID/sportbukkit
    args:
      - compile
  - name: gcr.io/cloud-builders/gsutil
    args:
      - -mq
      - cp
      - -r
      - .m2
      - gs://artifacts.$PROJECT_ID.appspot.com/artifacts/$BRANCH_NAME
